"""LoRA 学習用 TOML / sample_prompts 書き出し。

Pi 側で固定テンプレ（SDXL LoRA: network_dim=8 / alpha=4 / lr=1e-4 / batch=1 /
8 epochs）から `dataset.toml` / `config.toml` / `sample_prompts.txt` を生成し、
`<NAS>/lora_work/<project>/` に置く。Agent は sync で local SSD へ取り込む。
"""

from __future__ import annotations

import os

from src.units.lora_train import nas_io

# SDXL 固定テンプレ（Phase 4 E 時点で UI からの調整は未サポート、手動編集可）
_DEFAULTS = {
    "resolution": 1024,
    "num_repeats": 10,
    "batch_size": 1,
    "epochs": 8,
    "learning_rate": 1e-4,
    "network_dim": 8,
    "network_alpha": 4,
    "save_every_n_epochs": 2,
    "save_precision": "fp16",
    "mixed_precision": "bf16",
    "optimizer_type": "AdamW8bit",
    "lr_scheduler": "cosine_with_restarts",
    "lr_warmup_steps": 0,
    "clip_skip": 2,
    "seed": 42,
    "max_train_steps": 0,  # 0 なら epochs を使う
}

_DEFAULT_SAMPLE_PROMPTS_TEMPLATE = (
    "{trigger}, 1girl, solo, upper body, looking at viewer, "
    "simple background --n lowres, bad anatomy, bad hands --w 1024 --h 1024 "
    "--d 1 --l 7 --s 24\n"
    "{trigger}, 1girl, full body, standing, cowboy shot, "
    "detailed background --n lowres, bad anatomy --w 832 --h 1216 "
    "--d 2 --l 7 --s 24\n"
)


def default_sample_prompts(trigger_word: str) -> str:
    return _DEFAULT_SAMPLE_PROMPTS_TEMPLATE.format(trigger=trigger_word)


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_dataset_toml(
    *, project_name: str, dataset_dir: str,
    resolution: int | None = None, num_repeats: int | None = None,
    batch_size: int | None = None,
) -> str:
    """kohya `--dataset_config` 用 TOML を生成する。

    `class_tokens` にはトリガーワード（= project_name）を入れ、各 caption に
    あらかじめ挿入してある想定（WD14 タグ付けで先頭挿入済み）。
    """
    res = int(resolution or _DEFAULTS["resolution"])
    rep = int(num_repeats or _DEFAULTS["num_repeats"])
    bsz = int(batch_size or _DEFAULTS["batch_size"])
    esc_dir = _toml_escape(dataset_dir)
    esc_trigger = _toml_escape(project_name)
    return (
        "[general]\n"
        f"enable_bucket = true\n"
        f"resolution = {res}\n"
        f"shuffle_caption = true\n"
        f"caption_extension = \".txt\"\n"
        f"keep_tokens = 1\n"
        "\n"
        "[[datasets]]\n"
        f"batch_size = {bsz}\n"
        "\n"
        "[[datasets.subsets]]\n"
        f"image_dir = \"{esc_dir}\"\n"
        f"num_repeats = {rep}\n"
        f"class_tokens = \"{esc_trigger}\"\n"
    )


def build_config_toml(
    *, project_name: str, base_model_path: str, output_dir: str,
    sample_prompts_path: str, logging_dir: str,
    dataset_config_path: str,
    overrides: dict | None = None,
) -> str:
    """sdxl_train_network.py 用 `--config_file` TOML。"""
    d = dict(_DEFAULTS)
    if overrides:
        for k, v in overrides.items():
            if v is not None:
                d[k] = v

    def q(v: str) -> str:
        return f'"{_toml_escape(v)}"'

    lines = [
        "# Auto-generated by lora_train.toml_builder (edit manually if needed)",
        f"pretrained_model_name_or_path = {q(base_model_path)}",
        f"dataset_config = {q(dataset_config_path)}",
        f"output_dir = {q(output_dir)}",
        f"output_name = {q(project_name)}",
        f"logging_dir = {q(logging_dir)}",
        f"sample_prompts = {q(sample_prompts_path)}",
        "sample_every_n_epochs = 1",
        f'save_precision = "{d["save_precision"]}"',
        f'mixed_precision = "{d["mixed_precision"]}"',
        f"save_every_n_epochs = {int(d['save_every_n_epochs'])}",
        f'save_model_as = "safetensors"',
        f"max_train_epochs = {int(d['epochs'])}",
        f"learning_rate = {float(d['learning_rate'])}",
        f"unet_lr = {float(d['learning_rate'])}",
        f"text_encoder_lr = {float(d['learning_rate']) / 2}",
        f'network_module = "networks.lora"',
        f"network_dim = {int(d['network_dim'])}",
        f"network_alpha = {float(d['network_alpha'])}",
        f'optimizer_type = "{d["optimizer_type"]}"',
        f'lr_scheduler = "{d["lr_scheduler"]}"',
        f"lr_warmup_steps = {int(d['lr_warmup_steps'])}",
        f"clip_skip = {int(d['clip_skip'])}",
        f"seed = {int(d['seed'])}",
        "xformers = true",
        "gradient_checkpointing = true",
        "cache_latents = true",
        "cache_latents_to_disk = true",
        "persistent_data_loader_workers = true",
        "max_data_loader_n_workers = 2",
    ]
    if int(d.get("max_train_steps") or 0) > 0:
        lines.append(f"max_train_steps = {int(d['max_train_steps'])}")
    return "\n".join(lines) + "\n"


def prepare_project_files(
    nas_base: str, datasets_subdir: str, work_subdir: str,
    project: dict, *,
    base_model_path: str,
    dataset_overrides: dict | None = None,
    config_overrides: dict | None = None,
) -> dict:
    """dataset.toml / config.toml / sample_prompts.txt を NAS 上に書き出す。"""
    name = project["name"]
    dataset_dir = nas_io.dataset_dir(nas_base, datasets_subdir, name)
    work = nas_io.ensure_work_dirs(nas_base, work_subdir, name)

    dataset_toml_path = os.path.join(work["base"], "dataset.toml")
    config_toml_path = os.path.join(work["base"], "config.toml")
    sample_prompts_path = os.path.join(work["base"], "sample_prompts.txt")

    dataset_toml = build_dataset_toml(
        project_name=name, dataset_dir=dataset_dir, **(dataset_overrides or {}),
    )
    config_toml = build_config_toml(
        project_name=name,
        base_model_path=base_model_path,
        output_dir=work["checkpoints"],
        sample_prompts_path=sample_prompts_path,
        logging_dir=work["logs"],
        dataset_config_path=dataset_toml_path,
        overrides=config_overrides,
    )
    sample_prompts = default_sample_prompts(name)

    for path, body in (
        (dataset_toml_path, dataset_toml),
        (config_toml_path, config_toml),
        (sample_prompts_path, sample_prompts),
    ):
        with open(path, "w", encoding="utf-8") as f:
            f.write(body)

    return {
        "work_dir": work["base"],
        "dataset_toml": dataset_toml_path,
        "config_toml": config_toml_path,
        "sample_prompts": sample_prompts_path,
        "output_dir": work["checkpoints"],
        "logging_dir": work["logs"],
    }
